[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Specify the micro-ROS distribution and transport type
board_microros_distro = jazzy
board_microros_transport = serial

; Dependencies: Pulls in the micro-ROS PlatformIO library
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    madhephaestus/ESP32Encoder @ ^0.11.7